### ISSUE TITLE
About environment and the optimisers

### ISSUE THREAD

**Issue by Moukahou** [bradezard131/oicr-pytorch#1]
Thank you for your implementation.
I met some import error when I trying to run your code,mat I know the information about your environment (like the version of torch and cuda and so on )?

and in OICR.ipynb,you import  optimisers, but it seems that there are no file named optimisers?

**Comment by bradezard131** [comment]
You can probably just drop that import. It was there earlier and is now a part of my [utilities package](https://github.com/bradezard131/pytorch-utilities) (fair warning, it's broken right now). It was only for toying with some new optimisation algorithms anyway.

Version of pytorch is 1.2 (latest stable) but should be functional with any 1.X release so long as you have torchvision 0.3.0 or higher (for the roi pooling ops). Cuda is 10.0 I think, not sure but since there's no manually compiled code that shouldn't be an issue.

I hadn't anticipated anyone looking at my implementation so there's probably more than a few things broken (e.g. I still haven't successfully trained the VGG implementation, only the alexnet one). I was mostly uploading for my own benefit to clear out my computer before I return home from abroad.

**Comment by Moukahou** [comment]
thank you for your answer!
